[build]
  command = "npm run build"
  publish = build/client

[functions]
  directory = "/.netlify/v1/functions/server"

# Redirect all requests to the Remix server function
[[redirects]]
  from = "/*"
  to = "/.netlify/v1/functions/server"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }
  