[build]
  command = "npm run build"
  publish = "public"

[functions]
  directory = "Netlify/functions"

# Redirect all requests to the Remix server function
[[redirects]]
  from = "/*"
  to = "/Netlify/functions/server"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }
  