[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build/client"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }
